// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto.Golnich.Infra;

namespace Projeto.Golnich.RH.Migrations
{
    [DbContext(typeof(Conexao))]
    [Migration("20211222161206_migration01")]
    partial class migration01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto.Golnich.Domain.Candidatos.Candidatos", b =>
                {
                    b.Property<int>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAtu")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCad")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("IdCandidato");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("Projeto.Golnich.Domain.Experiencias.Experiencias", b =>
                {
                    b.Property<int>("IdExperiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cargo")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<DateTime>("DataAtu")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCad")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime");

                    b.Property<int>("Descricao")
                        .HasColumnType("int")
                        .HasMaxLength(4000);

                    b.Property<int>("Empresa")
                        .HasColumnType("int")
                        .HasMaxLength(100);

                    b.Property<int>("IdCandidato")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdExperiencia");

                    b.HasIndex("IdCandidato");

                    b.ToTable("Experiencias");
                });

            modelBuilder.Entity("Projeto.Golnich.Domain.Experiencias.Experiencias", b =>
                {
                    b.HasOne("Projeto.Golnich.Domain.Candidatos.Candidatos", "CandidatosNav")
                        .WithMany("Experiencias")
                        .HasForeignKey("IdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
